apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace = 'com.onyx.android.eink.pen.demo'
    compileSdk = rootProject.ext.compileSdk

    defaultConfig {
        applicationId = "com.android.onyx.eink.pen.demo"
        minSdk = 26
        targetSdk = rootProject.ext.targetSdk
        versionCode = 1
        versionName = "1.0"
        multiDexEnabled = true
        testInstrumentationRunner = 'androidx.test.runner.AndroidJUnitRunner'

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }

        sourceSets.main {
            aidl.srcDirs = ['src/main/java']
            jniLibs.srcDir 'src/main/libs'
            jni.srcDirs = []
        }
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = rootProject.ext.javaVersion
        targetCompatibility = rootProject.ext.javaVersion
    }

    buildFeatures {
        dataBinding = true
        aidl = true
    }

    packaging {
        resources {
            excludes += [
                    'META-INF/DEPENDENCIES',
                    'META-INF/LICENSE',
                    'META-INF/LICENSE.txt',
                    'META-INF/license.txt',
                    'META-INF/NOTICE',
                    'META-INF/NOTICE.txt',
                    'META-INF/notice.txt',
                    'META-INF/ASL2.0'
            ]
        }
        jniLibs {
            pickFirsts += ['lib/*/libc++_shared.so']
            excludes += ['lib/*/libc++.so']
        }
    }

    lint {
        abortOnError = false
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation "androidx.recyclerview:recyclerview:1.0.0"

    implementation('com.onyx.android.sdk:onyxsdk-pen:1.5.4.4')
    implementation 'org.lsposed.hiddenapibypass:hiddenapibypass:4.3'
}
